@startuml
!include ../style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>> {
class ContactList

Package Contact <<Rectangle>> {
class UniqueContactList
class Name
class Email
class Telegram
class Contact
}

Package Tag {
Class Tag
}
}

ContactList *-down-> "1" UniqueContactList

UniqueContactList o-down->"*" Contact

Contact *-->"1" Name
Contact *-->"1" Email
Contact *-->"0..1" Telegram
Contact *-->"0..*" Tag

@enduml
