@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant "command :ListConsumptionCommand" as ListConsumptionCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("calories")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("calories")
activate WishfulShrinkingParser

create ListConsumptionCommand
WishfulShrinkingParser -> ListConsumptionCommand
activate ListConsumptionCommand

ListConsumptionCommand --> WishfulShrinkingParser
deactivate ListConsumptionCommand

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> ListConsumptionCommand : execute()
activate ListConsumptionCommand

ListConsumptionCommand -> Model : getFilteredConsumptionList()
activate Model

Model --> ListConsumptionCommand : ObservableList<Consumption>
deactivate Model

create CommandResult
ListConsumptionCommand -> CommandResult
activate CommandResult

CommandResult --> ListConsumptionCommand
deactivate CommandResult

ListConsumptionCommand --> LogicManager : result
deactivate ListConsumptionCommand

[<--LogicManager
deactivate LogicManager
@enduml
