@startuml

!include ../style.puml
skinparam arrowThickness 0.6
skinparam arrowColor LOGIC_COLOR
skinparam classBackgroundColor LOGIC_COLOR



class ContactName
class Email
class Telegram

EditContactDescriptor *--"0..1" ContactName
EditContactDescriptor *--"0..1" Email
EditContactDescriptor *--"0..1" Telegram
EditContactDescriptor *--"*" Tag
EditContactDescriptor *--"1" boolean: isTelegramDeleted

@enduml
