@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":GetEditRecipeCommandParser" as GetEditRecipeCommandParser LOGIC_COLOR
participant "command :GetEditRecipeCommand" as GetEditRecipeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("editR 1")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("editR 1")
activate WishfulShrinkingParser

create GetEditRecipeCommandParser
WishfulShrinkingParser -> GetEditRecipeCommandParser
activate GetEditRecipeCommandParser

GetEditRecipeCommandParser --> WishfulShrinkingParser
deactivate GetEditRecipeCommandParser

WishfulShrinkingParser -> GetEditRecipeCommandParser : parse("1")
activate GetEditRecipeCommandParser

create GetEditRecipeCommand
GetEditRecipeCommandParser -> GetEditRecipeCommand
activate GetEditRecipeCommand

GetEditRecipeCommand --> GetEditRecipeCommandParser : command
deactivate GetEditRecipeCommand

GetEditRecipeCommandParser --> WishfulShrinkingParser : command
deactivate GetEditRecipeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetEditRecipeCommandParser -[hidden]-> WishfulShrinkingParser
destroy GetEditRecipeCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> GetEditRecipeCommand : execute()
activate GetEditRecipeCommand

create CommandResult
GetEditRecipeCommand -> CommandResult
activate CommandResult

CommandResult --> GetEditRecipeCommand

GetEditRecipeCommand -> CommandResult : setCommandBox(recipeCommand)

CommandResult --> GetEditRecipeCommand

GetEditRecipeCommand --> LogicManager : CommandResult
deactivate GetEditRecipeCommand

[<--LogicManager
deactivate LogicManager
@enduml
