@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":GetEditIngredientCommandParser" as GetEditIngredientCommandParser LOGIC_COLOR
participant "command :GetEditIngredientCommand" as GetEditIngredientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

[-> LogicManager : execute("editF 1")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("editF 1")
activate WishfulShrinkingParser

create GetEditIngredientCommandParser
WishfulShrinkingParser -> GetEditIngredientCommandParser
activate GetEditIngredientCommandParser

GetEditIngredientCommandParser --> WishfulShrinkingParser
deactivate GetEditIngredientCommandParser

WishfulShrinkingParser -> GetEditIngredientCommandParser : parse("1")
activate GetEditIngredientCommandParser

create GetEditIngredientCommand
GetEditIngredientCommandParser -> GetEditIngredientCommand
activate GetEditIngredientCommand

GetEditIngredientCommand --> GetEditIngredientCommandParser : command
deactivate GetEditIngredientCommand

GetEditIngredientCommandParser --> WishfulShrinkingParser : command
deactivate GetEditIngredientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
GetEditIngredientCommandParser -[hidden]-> WishfulShrinkingParser
destroy GetEditIngredientCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> GetEditIngredientCommand : execute()
activate GetEditIngredientCommand

create CommandResult
GetEditIngredientCommand -> CommandResult
activate CommandResult

CommandResult --> GetEditIngredientCommand

GetEditIngredientCommand -> CommandResult : setCommandBox(ingredientCommand)

CommandResult --> GetEditIngredientCommand

GetEditIngredientCommand --> LogicManager : CommandResult
deactivate GetEditIngredientCommand

[<--LogicManager
deactivate LogicManager
@enduml
