@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant "l:ListIngredientsCommand" as ListIngredientsCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":WishfulShrinking" as WishfulShrinking MODEL_COLOR
end box

[-> LogicManager : execute("fridge")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("fridge")
activate WishfulShrinkingParser

create ListIngredientsCommand
WishfulShrinkingParser -> ListIngredientsCommand
activate ListIngredientsCommand

ListIngredientsCommand --> WishfulShrinkingParser
deactivate ListIngredientsCommand

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> ListIngredientsCommand : execute()
activate ListIngredientsCommand

ListIngredientsCommand -> Model :  getFilteredIngredientList()
activate Model

Model -> WishfulShrinking : getIngredientList()
activate WishfulShrinking

WishfulShrinking -> Model: FilteredList<Ingredient>
deactivate WishfulShrinking

Model -> ListIngredientsCommand: ObservableList<Ingredient>
deactivate Model

create CommandResult
ListIngredientsCommand -> CommandResult
activate CommandResult

CommandResult --> ListIngredientsCommand
deactivate CommandResult

ListIngredientsCommand --> LogicManager : result
deactivate ListIngredientsCommand

[<--LogicManager
deactivate LogicManager
@enduml
