@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InventoryinatorParser" as InventoryinatorParser LOGIC_COLOR
participant ":DeleteItemCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteItemCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : input Command "deli -n bob's toenail")
activate LogicManager

LogicManager -> InventoryinatorParser : parseCommand("deli -n bob's toenail")
activate InventoryinatorParser
deactivate LogicManager

create DeleteCommandParser
InventoryinatorParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> InventoryinatorParser : parse("bob's toenail")

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : deleteItemCommand
deactivate DeleteCommand

DeleteCommandParser --> InventoryinatorParser : deleteItemCommand
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> InventoryinatorParser
destroy DeleteCommandParser

InventoryinatorParser --> LogicManager : deleteItemCommand
activate LogicManager
deactivate InventoryinatorParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : getItem("bob's toenail")
activate Model

Model --> DeleteCommand : Item
deactivate Model

DeleteCommand -> Model :deleteItem(Item)
activate Model
Model --> DeleteCommand

DeleteCommand -> Model : deleteRecipes(Item)
Model --> DeleteCommand
create CommandResult
DeleteCommand -> CommandResult
DeleteCommand -[hidden]-> LogicManager
destroy DeleteCommand
activate CommandResult

CommandResult --> LogicManager : CommandResult
deactivate CommandResult

[<--LogicManager : Output to User Interface
deactivate LogicManager
@enduml
