@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":AddRecipeCommandParser" as AddRecipeCommandParser LOGIC_COLOR
participant "command :AddRecipeCommand" as AddRecipeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":WishfulShrinking" as WishfulShrinking MODEL_COLOR
participant ":UniqueRecipeList" as UniqueRecipeList MODEL_COLOR
end box

[-> LogicManager : execute("addR n/Salad \n i/Veggies - 100g \n img/images/healthy3.jpg \n instr/Eat tag/healthy")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("addR n/Salad \n i/Veggies - 100g \n img/images/healthy3.jpg \n instr/Eat tag/healthy")
activate WishfulShrinkingParser

create AddRecipeCommandParser
WishfulShrinkingParser -> AddRecipeCommandParser
activate AddRecipeCommandParser

AddRecipeCommandParser --> WishfulShrinkingParser
deactivate AddRecipeCommandParser

WishfulShrinkingParser -> AddRecipeCommandParser : parse("n/Salad \n i/Veggies - 100g \n img/images/healthy3.jpg \n instr/Eat tag/healthy")
activate AddRecipeCommandParser

create AddRecipeCommand
AddRecipeCommandParser -> AddRecipeCommand
activate AddRecipeCommand

AddRecipeCommand --> AddRecipeCommandParser
deactivate AddRecipeCommand

AddRecipeCommandParser --> WishfulShrinkingParser : command
deactivate AddRecipeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddRecipeCommandParser -[hidden]-> WishfulShrinkingParser
destroy AddRecipeCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> AddRecipeCommand : execute(model)
activate AddRecipeCommand

AddRecipeCommand -> Model : addRecipe(recipe)
activate Model

Model -> WishfulShrinking : addRecipe(recipe)
activate WishfulShrinking

WishfulShrinking --> UniqueRecipeList: add(recipe)
activate UniqueRecipeList

UniqueRecipeList --> WishfulShrinking
deactivate UniqueRecipeList

WishfulShrinking --> Model
deactivate WishfulShrinking

Model --> AddRecipeCommand
deactivate Model

create CommandResult
AddRecipeCommand -> CommandResult
activate CommandResult

CommandResult --> AddRecipeCommand
deactivate CommandResult

AddRecipeCommand --> LogicManager : result
deactivate AddRecipeCommand

[<--LogicManager
deactivate LogicManager
@enduml
