@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandParser" as CommandParser LOGIC_COLOR
participant "<<class>>\n:DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "<<class>>\n:CommonParser" as CommonParser LOGIC_COLOR
participant "d:DeleteRecipeCommand" as DeleteRecipeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":HistoryManager" as HistoryManager LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete recipe #1")
activate LogicManager

LogicManager -> CommandParser : parse("delete recipe #1")
activate CommandParser

CommandParser -> CommandParser : parseArgs("delete recipe #1")
activate CommandParser
CommandParser --> CommandParser : "recipe #1"
deactivate CommandParser

CommandParser -> DeleteCommandParser : parseDeleteCommand("recipe #1")
activate DeleteCommandParser

DeleteCommandParser -> CommonParser : getCommandTarget("recipe #1")
activate CommonParser
CommonParser --> DeleteCommandParser : "recipe"
deactivate CommonParser

DeleteCommandParser -> DeleteCommandParser : parseDeleteRecipeCommand("recipe", "#1")
activate DeleteCommandParser

create DeleteRecipeCommand
DeleteCommandParser -> DeleteRecipeCommand
activate DeleteRecipeCommand

DeleteRecipeCommand --> DeleteCommandParser : d
deactivate DeleteRecipeCommand

DeleteCommandParser --> DeleteCommandParser : d
deactivate DeleteCommandParser

DeleteCommandParser --> CommandParser : d
deactivate DeleteCommandParser

CommandParser --> LogicManager : d
deactivate CommandParser

LogicManager -> DeleteRecipeCommand : execute()
activate DeleteRecipeCommand

DeleteRecipeCommand -> Model : deleteRecipe(1)
activate Model

Model --> DeleteRecipeCommand
deactivate Model

create CommandResult
DeleteRecipeCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteRecipeCommand
deactivate CommandResult

DeleteRecipeCommand --> LogicManager : result
deactivate DeleteRecipeCommand

LogicManager -> HistoryManager : add(d)
activate HistoryManager
deactivate HistoryManager

[<--LogicManager
deactivate LogicManager
@enduml
