@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":AddIngredientCommandParser" as AddIngredientCommandParser LOGIC_COLOR
participant "command :AddIngredientCommand" as AddIngredientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":WishfulShrinking" as WishfulShrinking MODEL_COLOR
participant ":UniqueIngredientList" as UniqueIngredientList MODEL_COLOR
end box

[-> LogicManager : execute("addF i/tomato")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("addF i/tomato")
activate WishfulShrinkingParser

create AddIngredientCommandParser
WishfulShrinkingParser -> AddIngredientCommandParser
activate AddIngredientCommandParser

AddIngredientCommandParser --> WishfulShrinkingParser
deactivate AddIngredientCommandParser

WishfulShrinkingParser -> AddIngredientCommandParser : parse("i/tomato")
activate AddIngredientCommandParser

create AddIngredientCommand
AddIngredientCommandParser -> AddIngredientCommand
activate AddIngredientCommand

AddIngredientCommand --> AddIngredientCommandParser : command
deactivate AddIngredientCommand

AddIngredientCommandParser --> WishfulShrinkingParser : command
deactivate AddIngredientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddIngredientCommandParser -[hidden]-> WishfulShrinkingParser
destroy AddIngredientCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> AddIngredientCommand : execute()
activate AddIngredientCommand

AddIngredientCommand -> Model : updateFilteredIngredientList(predicate)
activate Model

Model --> AddIngredientCommand
deactivate Model

AddIngredientCommand -> Model : addIngredient("tomato")
activate Model

Model -> WishfulShrinking : addIngredient("tomato")
activate WishfulShrinking

WishfulShrinking --> UniqueIngredientList: add("tomato")
activate UniqueIngredientList

UniqueIngredientList --> WishfulShrinking
deactivate UniqueIngredientList

WishfulShrinking --> Model
deactivate WishfulShrinking

Model --> AddIngredientCommand
deactivate Model

create CommandResult
AddIngredientCommand -> CommandResult
activate CommandResult

CommandResult --> AddIngredientCommand
deactivate CommandResult

AddIngredientCommand --> LogicManager : result
deactivate AddIngredientCommand

[<--LogicManager
deactivate LogicManager
@enduml
