@startuml
autoactivate on
!include ./style.puml

Participant ":Planus" as planus LOGIC_COLOR
Participant ":Lesson" as lesson LOGIC_COLOR
Participant ":Task" as task LOGIC_COLOR

[-> planus: addLesson(lesson)
planus -> lesson: createRecurringTasks()
loop all time slots for lesson events
create task
lesson -> task
task --> lesson
end
lesson --> planus: recurringTasks
loop all tasks created
planus -> planus: addTask(task)
return
planus -> planus: addTaskToCalendar(task)
return
end
return

@enduml
