@startuml
!include style.puml

group Parse AddMultipleChoiceQuestionCommand
box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":QuickCacheParser" as QuickCacheParser LOGIC_COLOR
participant ":AddMultipleChoiceQuestionCommandParser" as AddMultipleChoiceQuestionCommandParser LOGIC_COLOR
participant "t:AddMultipleChoiceQuestionCommand" as AddMultipleChoiceQuestionCommand LOGIC_COLOR
end box

activate LogicManager

LogicManager -> QuickCacheParser : parseCommand("add q/question ans/1 c/first c/second")
activate QuickCacheParser

create AddMultipleChoiceQuestionCommandParser
QuickCacheParser -> AddMultipleChoiceQuestionCommandParser
activate AddMultipleChoiceQuestionCommandParser

AddMultipleChoiceQuestionCommandParser -> QuickCacheParser
deactivate AddMultipleChoiceQuestionCommandParser

QuickCacheParser -> AddMultipleChoiceQuestionCommandParser : parse("q/question ans/1 c/first c/second")
activate AddMultipleChoiceQuestionCommandParser

create AddMultipleChoiceQuestionCommand
AddMultipleChoiceQuestionCommandParser -> AddMultipleChoiceQuestionCommand
activate AddMultipleChoiceQuestionCommand

AddMultipleChoiceQuestionCommand --> AddMultipleChoiceQuestionCommandParser : t
deactivate AddMultipleChoiceQuestionCommand

AddMultipleChoiceQuestionCommandParser -> QuickCacheParser : t
deactivate AddMultipleChoiceQuestionCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddMultipleChoiceQuestionCommandParser -[hidden]-> QuickCacheParser
destroy AddMultipleChoiceQuestionCommandParser

QuickCacheParser --> LogicManager : t
deactivate QuickCacheParser
end
@enduml
