@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "t:AddOpenEndedQuestionCommand" as AddOpenEndedQuestionCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":QuickCache" as QuickCache MODEL_COLOR
participant "flashcards:UniqueFlashcardList" as Flashcards MODEL_COLOR
participant "internalList:ObservableList<Flashcard>" as ObservableList MODEL_COLOR
end box
[-> LogicManager : execute("add q/question ans/answer")
activate LogicManager

ref over LogicManager, AddOpenEndedQuestionCommand : Parse AddOpenEndedQuestionCommand


LogicManager -> AddOpenEndedQuestionCommand : execute()
activate AddOpenEndedQuestionCommand

AddOpenEndedQuestionCommand -> Model : addFlashcard()
activate Model

Model -> QuickCache :addFlashcard()
activate QuickCache

QuickCache -> Flashcards :addFlashcard()
activate Flashcards

Flashcards -> ObservableList : add()
activate ObservableList
return

return

return

return

return result

AddOpenEndedQuestionCommand -[hidden]-> LogicManager
destroy AddOpenEndedQuestionCommand

[<--LogicManager
deactivate LogicManager
@enduml
