@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ClientListParser" as ClientListParser LOGIC_COLOR
participant ":AddPolicyCommandParser" as AddPolicyCommandParser LOGIC_COLOR
participant "a:AddPolicyCommand" as AddPolicyCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("addp n/ Star Assure d/ Protection against death and terminal illness")
activate LogicManager

LogicManager -> ClientListParser : parseCommand("addp n/ Star Assure d/ Protection against death and terminal illness")
activate ClientListParser

create AddPolicyCommandParser
ClientListParser -> AddPolicyCommandParser
activate AddPolicyCommandParser

AddPolicyCommandParser --> ClientListParser
deactivate AddPolicyCommandParser

ClientListParser -> AddPolicyCommandParser : parse("n/ Star Assure d/ Protection against death and terminal illness")
activate AddPolicyCommandParser

create AddPolicyCommand
AddPolicyCommandParser -> AddPolicyCommand
activate AddPolicyCommand

AddPolicyCommand --> AddPolicyCommandParser : a
deactivate AddPolicyCommand

AddPolicyCommandParser --> ClientListParser : a
deactivate AddPolicyCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddPolicyCommandParser -[hidden]-> ClientListParser
destroy AddPolicyCommandParser

ClientListParser --> LogicManager : a
deactivate ClientListParser

LogicManager -> AddPolicyCommand : execute()
activate AddPolicyCommand

AddPolicyCommand -> Model : addPolicy("Star Assure", "Protection against death and terminal illness")
activate Model

Model --> AddPolicyCommand
deactivate Model

create CommandResult
AddPolicyCommand -> CommandResult
activate CommandResult

CommandResult --> AddPolicyCommand
deactivate CommandResult

AddPolicyCommand --> LogicManager : result
deactivate AddPolicyCommand

[<--LogicManager
deactivate LogicManager
@enduml
