@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":MainCatalogueParser" as MainCatalogueParser LOGIC_COLOR
participant ":AddTeammateCommandParser" as AddTeammateCommandParser LOGIC_COLOR
participant ":AddTeammateCommand" as AddTeammateCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "Electrek:Project" as Project MODEL_COLOR
end box

[-> LogicManager : execute("addteammate...")
activate LogicManager

LogicManager -> Model: getStatus()
activate Model

Model --> LogicManager: status
deactivate Model

LogicManager -> MainCatalogueParser : parseCommand("addteammate...", status)
activate MainCatalogueParser

create AddTeammateCommandParser
MainCatalogueParser -> AddTeammateCommandParser
activate AddTeammateCommandParser

AddTeammateCommandParser --> MainCatalogueParser
deactivate AddTeammateCommandParser

MainCatalogueParser -> AddTeammateCommandParser : parse("addteammate...")
activate AddTeammateCommandParser

create AddTeammateCommand
AddTeammateCommandParser -> AddTeammateCommand
activate AddTeammateCommand

AddTeammateCommand --> AddTeammateCommandParser : teammate
deactivate AddTeammateCommand

AddTeammateCommandParser --> MainCatalogueParser : teammate
deactivate AddTeammateCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddTeammateCommandParser -[hidden]-> MainCatalogueParser


MainCatalogueParser --> LogicManager : teammate
deactivate MainCatalogueParser

LogicManager -> AddTeammateCommand : execute()
activate AddTeammateCommand

AddTeammateCommand -> Model : getProjectToBeDisplayedOnDashboard().get()
activate Model

Model --> AddTeammateCommand : Electrek
deactivate Model

AddTeammateCommand -> Project : addProject(project)
activate Project

Project --> AddTeammateCommand :
deactivate Project

create CommandResult
AddTeammateCommand -> CommandResult
activate CommandResult

CommandResult --> AddTeammateCommand
deactivate CommandResult

AddTeammateCommand --> LogicManager : result
deactivate AddTeammateCommand

[<--LogicManager
deactivate LogicManager
@enduml
