@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ReeveParser" as ReeveParser LOGIC_COLOR
participant ":QuestionCommandParser" as QuestionCommandParser LOGIC_COLOR
participant "a:AddQuestionCommand" as AddQuestionCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "student:Student" as Student MODEL_COLOR
end box

[-> LogicManager : execute(...)
activate LogicManager

LogicManager -> ReeveParser : parseCommand(...)
activate ReeveParser

create QuestionCommandParser
ReeveParser -> QuestionCommandParser
activate QuestionCommandParser

QuestionCommandParser --> ReeveParser
deactivate QuestionCommandParser

ReeveParser -> QuestionCommandParser : parse(...)
activate QuestionCommandParser

create AddQuestionCommand
QuestionCommandParser -> AddQuestionCommand
activate AddQuestionCommand

AddQuestionCommand --> QuestionCommandParser : a
deactivate AddQuestionCommand

QuestionCommandParser --> ReeveParser : a
deactivate QuestionCommandParser

QuestionCommandParser -[hidden]-> ReeveParser
destroy QuestionCommandParser

ReeveParser --> LogicManager : a
deactivate ReeveParser

LogicManager -> AddQuestionCommand : execute()
activate AddQuestionCommand

AddQuestionCommand -> Student : addQuestion(q)
activate Student

Student --> AddQuestionCommand : copy
deactivate Student

AddQuestionCommand -> Model : setStudent(student, copy)
activate Model

Student -[hidden]-> Model
destroy Student

Model --> AddQuestionCommand
deactivate Model

AddQuestionCommand --> LogicManager : result
deactivate AddQuestionCommand

AddQuestionCommand -[hidden]-> LogicManager
destroy AddQuestionCommand

[<-- LogicManager
deactivate LogicManager
@enduml
