@startuml
!include style.puml

start
:User executes add question command;
:Parses the command;
if () then ([command is invalid])
    :Display parse error message;
else ([else])
    :AddQuestionCommand is executed;
        if () then ([student does not exists])
            :Display invalid student error message;
        else ([else])
            :Add question to student <$rake>;
        endif
endif
stop


partition "Activity: Add question to student" {
    start
    if () then ([else])
        :Create student copy;
        :Add question to student copy;
        :Replace student with modified copy;
        :Display success message;
    else ([has duplicate question])
        :Display duplicate question error message;
    endif
    stop
}

@enduml
