@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ExpenseBookParser" as ExpenseBookParser LOGIC_COLOR
participant "s:AliasCommand" as AliasCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("alias find get")
activate LogicManager

LogicManager -> ExpenseBookParser : parseCommand("alias find get")
activate ExpenseBookParser

create AliasCommand
ExpenseBookParser -> AliasCommand
activate AliasCommand

AliasCommand --> ExpenseBookParser
deactivate AliasCommand

ExpenseBookParser --> LogicManager : s
deactivate ExpenseBookParser

LogicManager -> AliasCommand : execute()
activate AliasCommand

AliasCommand -> Model : setAlias(prev, new)
activate Model

Model --> AliasCommand
deactivate Model

deactivate AliasCommand
AliasCommand --> LogicManager : result
destroy AliasCommand

[<--LogicManager
deactivate LogicManager
@enduml
