@startuml
!include style.puml

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
participant "commandTextField:TextField" as TextField UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant "<<class>>\n:AutocompleteModule" as AutocompleteModule LOGIC_COLOR
participant "acMod:AutocompleteModule" as AcModuleInstance LOGIC_COLOR
participant "cname:Suggestion" as Suggestion LOGIC_COLOR
end box


MainWindow -> AutocompleteModule : attachTo(commandTextField)
activate AutocompleteModule


create AcModuleInstance
AutocompleteModule -> AcModuleInstance : new AutocompleteModule(commandTextField)
activate AcModuleInstance
AcModuleInstance -> AcModuleInstance : setupAutocompleteActionKeys();
activate AcModuleInstance
AcModuleInstance -> TextField : addEventFilter(event, actionKeysHandler)
AcModuleInstance --> AcModuleInstance
deactivate AcModuleInstance
||||
AcModuleInstance -> AcModuleInstance : disableFocusTraversal()
activate AcModuleInstance
AcModuleInstance --> AcModuleInstance
deactivate AcModuleInstance
AcModuleInstance --> AutocompleteModule
deactivate AcModuleInstance


AutocompleteModule --> MainWindow
deactivate AutocompleteModule




MainWindow -> AcModuleInstance : addSuggestions("cname/",\n () -> List.of("Alice","Bob", "Charlie"))
activate AcModuleInstance

create Suggestion
AcModuleInstance -> Suggestion
activate Suggestion
Suggestion --> AcModuleInstance
deactivate Suggestion
deactivate AcModuleInstance

@enduml
