@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

McGymmy *-down-> "1" Fridge
TagSet -[hidden]down- Fridge
TagSet -[hidden]down- Fridge


Fridge o-down-> Food


Food *--> "1" Name
Food *--> "1" Protein
Food *--> "1" Carbohydrate
Food *--> "1" Fat
Food *--> "1" Date
Food *--> "1" TagSet
TagSet *-right-> "*" Tag
@enduml
