@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

FitNus *-right-> "1" UniqueExerciseList
FitNus *-down-> "1" UniqueLessonList

FitNus *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueExerciseList
UniqueLessonList -[hidden]down- UniqueExerciseList

UniqueTagList *-right-> "*" Tag
UniqueExerciseList o-right-> Exercise
UniqueLessonList o-right-> Lesson


Exercise o-up-> "*" Tag
Lesson o-up-> "*" Tag

Lesson *--> Name
Exercise *--> Name

@enduml
