@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ExerciseBook *-> "1" UniqueExerciseList
ExerciseBook *-> "1" UniqueExerciseTagList
ExerciseBook *-> "1" UniqueMuscleTagList
UniqueExerciseTagList -[hidden]down- UniqueExerciseList
UniqueMuscleTagList -[hidden]down- UniqueExerciseList


UniqueExerciseTagList *--> "*" ExerciseTag
UniqueMuscleTagList *--> "*"MuscleTag
UniqueExerciseList o-right-> Exercise
UniqueExerciseList *-right[hidden]-> MuscleTag

Exercise o-up-> "*" ExerciseTag
Exercise o-up-> "*" MuscleTag

Exercise *--> Name
Exercise *--> Date
Exercise *--> Description
Exercise *--> Calories
@enduml
