@startuml
start
:User executes cclear command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([contact list is not empty])
    :Clear contacts from the contact list;
    :Update GUI to show empty contact list;
else ([else])
    :Show error message;
endif
stop
@enduml
