@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommonCentsParser" as CommonCentsParser LOGIC_COLOR
participant ":ClearCommandParser" as ClearCommandParser LOGIC_COLOR
participant ":ClearCommand" as ClearCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":ActiveAccountManager" as ActiveAccount MODEL_COLOR
participant ":ModelManager" as Model MODEL_COLOR
end box

[-> LogicManager : execute("clear c/expense")
activate LogicManager

LogicManager -> CommonCentsParser: parseCommand("clear c/expense")
activate CommonCentsParser

CommonCentsParser -> ClearCommandParser: parse("clear c/expense")
activate ClearCommandParser

create ClearCommand
ClearCommandParser -> ClearCommand
activate ClearCommand

ClearCommand -> ClearCommandParser
deactivate ClearCommand

ClearCommandParser --> CommonCentsParser
deactivate ClearCommandParser

CommonCentsParser --> LogicManager
deactivate CommonCentsParser

LogicManager -> ClearCommand: execute(model, activeAccount)
activate ClearCommand

alt isExpense
ClearCommand -> ActiveAccount: clearExpense()
activate ActiveAccount
else
end


alt isRevenue
ClearCommand -> ActiveAccount: clearRevenue()
else
end

alt isNoCategoryPresent
ClearCommand -> ActiveAccount: clearRevenue()
ClearCommand -> ActiveAccount: clearExpense()
else
end

ActiveAccount -> Model: setAccount(editedAccount)
activate Model

deactivate ActiveAccount
deactivate Model

ClearCommand --> LogicManager
deactivate ClearCommand

deactivate LogicManager
@enduml
