@startuml
start
:User executes clearstats command;
:Model returns the previously filtered list;
:Search for flashcard matching the index given;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([given flashcard index is valid])
    :Get a copy of the flashcard with the
    statistics set to zero for all attributes;
    :Replace old flashcard with updated
    flashcard;
    :Pass the result to the UI;
else ([else])
    :Throw CommandException;
    :Pass the CommandException to the UI;
endif
    :UI displays results to User;
stop
@enduml
