@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":ClearTagCommandParser" as ClearTagCommandParser LOGIC_COLOR
participant ":ParserUtil" as ParserUtil LOGIC_COLOR
participant "c:ClearTagCommand" as ClearTagCommand LOGIC_COLOR
participant "clearedPerson:Person" as Person LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("tag clear Alex Yeoh")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("tag clear Alex Yeoh")
activate AddressBookParser

create ClearTagCommandParser
AddressBookParser -> ClearTagCommandParser : ClearTagCommandParser()
activate ClearTagCommandParser

ClearTagCommandParser --> AddressBookParser
deactivate ClearTagCommandParser

AddressBookParser -> ClearTagCommandParser : parse("Alex Yeoh")
activate ClearTagCommandParser

ClearTagCommandParser -> ParserUtil : parseName("Alex Yeoh")
activate ParserUtil

ParserUtil --> ClearTagCommandParser : name
deactivate ParserUtil

create ClearTagCommand
ClearTagCommandParser -> ClearTagCommand : ClearTagCommand(name);
activate ClearTagCommand

ClearTagCommand --> ClearTagCommandParser : c
deactivate ClearTagCommand

ClearTagCommandParser --> AddressBookParser : c
destroy ClearTagCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> ClearTagCommand : execute()
activate ClearTagCommand

create Person
ClearTagCommand -> Person : Person(p.getName(), p.getPhone(), p.getEmail(), new HashSet<>())
activate Person

Person --> ClearTagCommand : clearedPerson
deactivate Person

ClearTagCommand -> Model : setPerson(p, clearedPerson)
activate Model

Model --> ClearTagCommand
deactivate Model

ClearTagCommand -> Model : updatePersonInMeetingBook(p, clearedPerson)
activate Model

Model --> ClearTagCommand
deactivate Model

ClearTagCommand -> Model : updatePersonInModuleBook(p, clearedPerson)
activate Model

Model --> ClearTagCommand
deactivate Model

create CommandResult
ClearTagCommand -> CommandResult
activate CommandResult

CommandResult --> ClearTagCommand
deactivate CommandResult

ClearTagCommand --> LogicManager : result
destroy ClearTagCommand

[<--LogicManager
deactivate LogicManager
@enduml
