@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant "c:ClearStatsCommand" as ClearStatsCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "lastShownList:ObservableList<Flashcard>" as ObservableList MODEL_COLOR
participant "flashcardToClearStatistics:Flashcard" as Flashcard MODEL_COLOR
participant "updatedFlashcard:Flashcard" as UpdatedFlashcard MODEL_COLOR
end box

[-> LogicManager : execute("clearstats 1")
activate LogicManager

ref over LogicManager, ClearStatsCommand : Parse ClearStats Command


LogicManager -> ClearStatsCommand : execute()
activate ClearStatsCommand

ClearStatsCommand -> Model : getFilteredFlashcardList()
activate Model

Model --> ClearStatsCommand : lastShownList
deactivate Model

ClearStatsCommand -> ObservableList : get(0)
activate ObservableList

ObservableList --> ClearStatsCommand : flashcardToClearStatistics
deactivate ObservableList

ClearStatsCommand -> Flashcard : getFlashcardAfterClearStatistics()
activate Flashcard

create UpdatedFlashcard
Flashcard -> UpdatedFlashcard
activate UpdatedFlashcard

UpdatedFlashcard --> Flashcard : updatedFlashcard
deactivate UpdatedFlashcard

Flashcard --> ClearStatsCommand : updatedFlashcard
deactivate Flashcard

ClearStatsCommand -> Model : setFlashcard(flashcardToClearStatistics, updatedFlashcard)
activate Model

destroy Flashcard

Model --> ClearStatsCommand
deactivate Model

ClearStatsCommand --> LogicManager : result
deactivate ClearStatsCommand

[<--LogicManager : result
deactivate LogicManager
destroy ClearStatsCommand
@enduml
