@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":EvaParser" as EvaParser LOGIC_COLOR
participant ":DeleteStaffCommandParser" as DeleteStaffCommandParser LOGIC_COLOR
participant "d:DeleteStaffCommand" as DeleteStaffCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("dels 1")
activate LogicManager

LogicManager -> EvaParser : parseCommand("dels 1")
activate EvaParser

create DeleteStaffCommandParser
EvaParser -> DeleteStaffCommandParser
activate DeleteStaffCommandParser

DeleteStaffCommandParser --> EvaParser
deactivate DeleteCommandParser

EvaParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> EvaParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> EvaParser
destroy DeleteCommandParser

EvaParser --> LogicManager : d
deactivate EvaParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deleteStaff(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
