@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":DeleteIngredientCommandParser" as DeleteIngredientCommandParser LOGIC_COLOR
participant "d:DeleteIngredientCommand" as DeleteIngredientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":WishfulShrinking" as WishfulShrinking MODEL_COLOR
participant ":UniqueIngredientList" as UniqueIngredientList MODEL_COLOR
end box

[-> LogicManager : execute("deleteR 1")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("deleteF 1")
activate WishfulShrinkingParser

create DeleteIngredientCommandParser
WishfulShrinkingParser -> DeleteIngredientCommandParser
activate DeleteIngredientCommandParser

DeleteIngredientCommandParser --> WishfulShrinkingParser
deactivate DeleteIngredientCommandParser

WishfulShrinkingParser -> DeleteIngredientCommandParser : parse("1")
activate DeleteIngredientCommandParser

create DeleteIngredientCommand
DeleteIngredientCommandParser -> DeleteIngredientCommand
activate DeleteIngredientCommand

DeleteIngredientCommand --> DeleteIngredientCommandParser : command
deactivate DeleteIngredientCommand

DeleteIngredientCommandParser --> WishfulShrinkingParser : command
deactivate DeleteIngredientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteIngredientCommandParser -[hidden]-> WishfulShrinkingParser
destroy DeleteIngredientCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> DeleteIngredientCommand : execute()
activate DeleteIngredientCommand

DeleteIngredientCommand -> Model : getFilteredIngredientList()
activate Model

Model -> WishfulShrinking : removeIngredient(key)
activate WishfulShrinking

WishfulShrinking -> UniqueIngredientList : remove(toRemove)
activate UniqueIngredientList

UniqueIngredientList -> WishfulShrinking
deactivate UniqueIngredientList

WishfulShrinking -> Model
deactivate WishfulShrinking

Model --> DeleteIngredientCommand
deactivate Model

create CommandResult
DeleteIngredientCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteIngredientCommand
deactivate CommandResult

DeleteIngredientCommand --> LogicManager : result
deactivate DeleteIngredientCommand

[<--LogicManager
deactivate LogicManager
@enduml
