@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":UntagCommandParser" as UntagCommandParser LOGIC_COLOR
participant "d:UntagCommand" as UntagCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("untag t>myTag")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("untag t>myTag")
activate AddressBookParser

create UntagCommandParser
AddressBookParser -> UntagCommandParser
activate UntagCommandParser

UntagCommandParser --> AddressBookParser
deactivate UntagCommandParser

AddressBookParser -> UntagCommandParser : parse("t>myTag")
activate UntagCommandParser

create UntagCommand
UntagCommandParser -> UntagCommand
activate UntagCommand

UntagCommand --> UntagCommandParser : d
deactivate UntagCommand

UntagCommandParser --> AddressBookParser : d
deactivate UntagCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
UntagCommandParser -[hidden]-> AddressBookParser
destroy UntagCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> UntagCommand : execute()
activate UntagCommand

UntagCommand -> Model : deleteTag(m)
activate Model

Model --> UntagCommand
deactivate Model

create CommandResult
UntagCommand -> CommandResult
activate CommandResult

CommandResult --> UntagCommand
deactivate CommandResult

UntagCommand --> LogicManager : result
deactivate UntagCommand

[<--LogicManager
deactivate LogicManager
@enduml
