@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":McGymmyParser" as McGymmyParser LOGIC_COLOR
participant ":PrimitiveCommandParser" as PrimitiveCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> McGymmyParser : parse("delete 1")
activate McGymmyParser

McGymmyParser -> PrimitiveCommandParser : parsePrimitiveCommand("delete", ["1"])
activate PrimitiveCommandParser

create DeleteCommand
PrimitiveCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> PrimitiveCommandParser : d
deactivate DeleteCommand

|||

PrimitiveCommandParser -> DeleteCommand : getParameterSet
activate DeleteCommand
DeleteCommand --> PrimitiveCommandParser
deactivate DeleteCommand

|||

PrimitiveCommandParser -> PrimitiveCommandParser : provideValuesToParameterSet
activate PrimitiveCommandParser
PrimitiveCommandParser --> PrimitiveCommandParser
deactivate PrimitiveCommandParser

PrimitiveCommandParser --> McGymmyParser : d
deactivate PrimitiveCommandParser

McGymmyParser --> LogicManager : d
deactivate McGymmyParser

LogicManager -> DeleteCommand : execute()
activate DeleteCommand

DeleteCommand -> Model : deletePerson(1)
activate Model

Model --> DeleteCommand
deactivate Model

|||

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
