@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":DeleteRecipeCommandParser" as DeleteRecipeCommandParser LOGIC_COLOR
participant "d:DeleteRecipeCommand" as DeleteRecipeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":WishfulShrinking" as WishfulShrinking MODEL_COLOR
participant ":UniqueRecipeList" as UniqueRecipeList MODEL_COLOR
end box

[-> LogicManager : execute("deleteR 1")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("deleteR 1")
activate WishfulShrinkingParser

create DeleteRecipeCommandParser
WishfulShrinkingParser -> DeleteRecipeCommandParser
activate DeleteRecipeCommandParser

DeleteRecipeCommandParser --> WishfulShrinkingParser
deactivate DeleteRecipeCommandParser

WishfulShrinkingParser -> DeleteRecipeCommandParser : parse("1")
activate DeleteRecipeCommandParser

create DeleteRecipeCommand
DeleteRecipeCommandParser -> DeleteRecipeCommand
activate DeleteRecipeCommand

DeleteRecipeCommand --> DeleteRecipeCommandParser : command
deactivate DeleteRecipeCommand

DeleteRecipeCommandParser --> WishfulShrinkingParser : command
deactivate DeleteRecipeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteRecipeCommandParser -[hidden]-> WishfulShrinkingParser
destroy DeleteRecipeCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> DeleteRecipeCommand : execute()
activate DeleteRecipeCommand

DeleteRecipeCommand -> Model : getFilteredRecipeList()
activate Model

Model -> WishfulShrinking : removeRecipe(key)
activate WishfulShrinking

WishfulShrinking -> UniqueRecipeList : remove(toRemove)
activate UniqueRecipeList

UniqueRecipeList -> WishfulShrinking
deactivate UniqueRecipeList

WishfulShrinking -> Model
deactivate WishfulShrinking

Model -> DeleteRecipeCommand
deactivate Model

Model --> DeleteRecipeCommand
deactivate Model

create CommandResult
DeleteRecipeCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteRecipeCommand
deactivate CommandResult

DeleteRecipeCommand --> LogicManager : result
deactivate DeleteRecipeCommand

[<--LogicManager
deactivate LogicManager
@enduml
