@startuml
!include style.puml

start

:User enters an DeleteModule
command in the command box;

:TrackrParser parses the argument
to determine which command parser
should further parse it;

:DeleteModuleCommandParser
parses the user input;

:ParserUtil parses User Input
to determine index of Module to Delete;

    if () then ([Trackr is in Module View])
        if () then ([else])
            :Module is deleted;
        else ([Index bigger than list of Modules])
            :throws CommandException with
            not in Module View error message;
        endif
    else ([else])
        :throws ParseException with
        module not edited message;
    endif
:returns feedback to user;

stop

@enduml