@startuml
start
:User executes delete command: delete 1;
:Logic executes delete command;
:DeleteCommandParser parses the command: delete 1;

if () then ([index > 0 and index is integer])
:execute DeleteCommand;

        if () then ([is valid index])
        :item is deleted;

        else ([is invalid index])
        :throw command exception;

        endif

else ([index <= 0 or index not integer])
    :throw parse exception;

endif
stop

@enduml
