@startuml
!include style.puml

start
:User executes delete question command;
:Parses the command;
if () then ([command is valid])
    :Execute DeleteQuestionCommand;
    if () then ([student exists])
        :Delete question from student <$rake>;

    else ([else])
        :Display invalid student error message;
    endif
else ([command is invalid])
    :Display parse error message;
endif
stop

partition "Activitiy: Delete question from student" {
start
if () then ([question exists])
    :Create student copy;
    :Delete question from student copy;
    :Replace student with modified copy;
    :Display success message;
else ([else])
    :Display invalid question error message;
endif
stop
}

@enduml
