@startuml
scale max 500 height

start
:User executes edit command;
:Model returns the previously filtered list;
:Search for flashcard matching the index given;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([given flashcard index is valid])
    :Create a new flashcard from
    combining User-specified flashcard
    and User-given descriptor;
    :Replace User-specified flashcard with new flashcard;
    :Pass edited flashcard to UI through feedback;
else ([else])
    :Throw CommandException;
    :UI catches CommandException;
endif
    :UI displays results to User;
stop
@enduml
