@startuml
!include style.puml

start

:User enters an Edit Module
command in the command box;

:TrackrParser parses the argument
to determine which command parser
should further parse it;

:EditModuleCommandParser
parses the user input;

:ParserUtil parses User Input
to determine index of Module to Edit;

    if () then ([At least one field edited])
        :User Input passed to ParserUtil
        to determine edited ModuleId;
        if () then ([Trackr is in Module View])
                if () then ([else])
                        :Module is edited;
                        :All Modules displayed by Trackr;
                else ([EditedModule already exists])
                        :throws CommandException with
                        duplicate module error message;
                endif
        else ([else])
            :throws CommandException with
            not in Module View error message;
        endif
    else ([else])
        :throws ParseException with
        module not edited message;
    endif
:returns feedback to user;

stop
@enduml
