@startuml
start
repeat :User enters command;
repeat  while () is ([invalid args])
'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.
-> [valid args];
:Account is retrieved from ActiveAccount;
:Account is edited in ActiveAccount;
:new Account's is retrieved from ActiveAccount;
:Account in Model is replaced with new Account;

stop
@enduml
