@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([favourite a flashcard])
        if () then ([flashcard is already favourited])
        else ([else])
            :Creates a flashcard that is favourited;
            :Replace the current flashcard with favourited flashcard;
        endif
else ([unfavourite a flashcard])
    if () then ([flashcard is already unfavourited])
    else ([else])
        :Creates a flashcard that is not favourited;
        :Replace the favourited flashcard with flashcard that is not favourited;
     endif
endif
stop
@enduml
