@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam defaultFontSize 12
scale 0.7

title After command "unfav 1"

package States {
    class FlashcardDeckState1 as "__fd1:ObservableList<Flashcard>__"

    class Flashcard1 as "__f1:Flashcard__"
    class Flashcard2 as "__f2:Flashcard__"
    class Flashcard3 as "__f3:Flashcard__"
}

Flashcard1 <--o FlashcardDeckState1
Flashcard2  <--o FlashcardDeckState1
Flashcard3  <--o FlashcardDeckState1

class Pointer as "Current State" #FFFFF
Pointer -up-> FlashcardDeckState1
@end
