@startuml
start
:User executes add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([f/ argument(s) specified])
    :ArgumentTokenizer parses feed times and other fields;
    :ParserUtil creates TreeSet<FeedTime> with comparator;
else ([else])
    :ArgumentTokenizer parses other fields;
endif
:Animal object is created with parsed fields;
stop
@enduml
