@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FlashcardDeckParser" as FlashcardDeckParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "f:FilterCommand" as FilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("filter c/SDLC r/3")
activate LogicManager

LogicManager -> FlashcardDeckParser : parseCommand("filter c/SDLC r/3")
activate FlashcardDeckParser

create FilterCommandParser
FlashcardDeckParser -> FilterCommandParser
activate FilterCommandParser

FilterCommandParser --> FlashcardDeckParser
deactivate FilterCommandParser

FlashcardDeckParser -> FilterCommandParser : parse("c/SDLC r/3")
activate FilterCommandParser

create FilterCommand
FilterCommandParser -> FilterCommand
activate FilterCommand

FilterCommand --> FilterCommandParser : f
deactivate FilterCommand

FilterCommandParser --> FlashcardDeckParser : f
deactivate FilterCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterCommandParser -[hidden]-> FlashcardDeckParser
destroy FilterCommandParser

FlashcardDeckParser --> LogicManager : f
deactivate FlashcardDeckParser

LogicManager -> FilterCommand : execute()
activate FilterCommand

FilterCommand -> Model : updateFilteredFlashcardList(predicate)
activate Model

Model --> FilterCommand
deactivate Model

create CommandResult
FilterCommand -> CommandResult
activate CommandResult

CommandResult --> FilterCommand
deactivate CommandResult

FilterCommand --> LogicManager : result
deactivate FilterCommand

[<--LogicManager
deactivate LogicManager
@enduml
