@startuml
!include ./style.puml

box "Logic" #LightBlue

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":ReeveParser" as rp LOGIC_COLOR
Participant ":FindCommandParser" as fcp LOGIC_COLOR
Participant ":FindStudentDescriptor" as fcd LOGIC_COLOR
Participant ":NameContainsKeywordsPredicate" as namePredicate LOGIC_COLOR
Participant ":SchoolContainsKeywordsPredicate" as schoolPredicate LOGIC_COLOR
Participant "command:FindCommand" as fc LOGIC_COLOR
Participant ":CommandResult" as res LOGIC_COLOR


[-> logic : execute
activate logic
logic -> rp ++: parseCommand(commandText)
create fcp
rp -> fcp
rp -> fcp ++: parse(args)
create fcd
fcp -> fcd
opt If finding by name

    create namePredicate
    fcp -> namePredicate: nameKeywords
    fcp -> fcd: setNamePredicate(NameContainsKeywordsPredicate)
    end

opt If finding by school

    create schoolPredicate
    fcp -> schoolPredicate: schoolKeywords
    fcp -> fcd: setSchoolPredicate(SchoolContainsKeywordsPredicate)
    end

fcp -> fcd: isAnyPredicatePresent()
create fc
fcp -> fc ++: findStudentDescriptor
return command
return command
return command
logic -> fc ++: execute(model)
fc -> fcd++: getPredicates()
fcd -> fcd: getNamePredicate()
fcd -> fcd: getSchoolPredicate()
fcd -> fcd: getYearPredicate()
return predicates


end box

box "Model" #Green
Participant ":Model" as model #77dd77

fc -> model++: updateFilteredPersonList(consolidatedPredicates)
return
fc -> model: getFilteredPersonList()
create res
fc -> res ++
return commandResult
return commandResult
return
end box

@enduml
