@startuml
start
:User executes Find command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([any of the keywords violate
           the given restrictions]
)
:Show error message;
else ([else]
)
    :Filters contact list according to keywords;
    :Update GUI to show filtered contact list;
endif
stop
@enduml
