@startuml
!include /style.puml
skinparam arrowThickness 1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR
left to right direction

class FindTaskCriteria {
    - List<Predicate<Task>> predicateList
}

interface Predicate {
	+ boolean test(Task task)
	+ boolean equals(Object other)
}

class TaskNameContainsKeywordsPredicate {
    - List<String> keywords
}

class TaskMatchesDatePredicate {
    - Date searchDate
}

class TaskMatchesPriorityPredicate {
    - Priority searchPriority
}

class TaskMatchesStatusPredicate {
    - Status searchPriority
}

class TaskContainsTagsPredicate {
    - Set<Tags> tags
}

FindTaskCriteria *--"1..5" Predicate
Predicate <|.. TaskNameContainsKeywordsPredicate
Predicate <|.. TaskMatchesDatePredicate
Predicate <|.. TaskMatchesPriorityPredicate
Predicate <|.. TaskMatchesStatusPredicate
Predicate <|.. TaskContainsTagsPredicate

@enduml
