@startuml
!include style.puml

Actor User

box UI UI_COLOR_T1
participant "commandTextField:TextField" as TextField UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant "fzfMod:FzfModule" as FzfModule LOGIC_COLOR
participant "query:TextField" as Query LOGIC_COLOR
end box

loop isFzfMode
    User -> TextField : Presses any key
    activate TextField
    TextField -> Query : fireEvent(keyPress)

    TextField -> Query  : getText()
    activate Query
    Query --> TextField : query
    deactivate Query

    TextField -> FzfModule : refreshMenu(query)
    activate FzfModule
    FzfModule -->TextField
    deactivate FzfModule

    TextField-[hidden]->User
    deactivate TextField
end

@enduml
