@startuml
start
:User executes get edit command: edit 1;
:Logic executes get edit command;
:GetEditCommandParser parses the command: edit 1;

if () then ([index > 0 and index is integer])
:execute GetEditCommand;

        if () then ([is valid index])
        :item is fetched;

        else ([is invalid index])
        :throw command exception;

        endif

else ([index <= 0 or index not integer])
    :throw parse exception;

endif
stop

@enduml
