@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommonCentsParser" as CommonCentsParser LOGIC_COLOR
participant ":GetTotalCommandParser" as GetTotalCommandParser LOGIC_COLOR
participant ":GetTotalCommand" as GetTotalCommand LOGIC_COLOR
end box

box Entry MODEL_COLOR_T1
participant ":Category" as Category MODEL_COLOR
end box

box ActiveAccount ACTIVEACCOUNT_COLOR_T1
participant ":ActiveAccountManager" as ActiveAccount LOGIC_COLOR
end box

[-> LogicManager : execute("total c/expense"")
activate LogicManager

LogicManager -> CommonCentsParser: parseCommand("total c/expense")
activate CommonCentsParser

CommonCentsParser -> GetTotalCommandParser: parse("total c/expense")
activate GetTotalCommandParser

create GetTotalCommand
GetTotalCommandParser -> GetTotalCommand
activate GetTotalCommand

GetTotalCommand --> GetTotalCommandParser
deactivate GetTotalCommand

GetTotalCommandParser --> CommonCentsParser
deactivate GetTotalCommandParser
deactivate CommonCentsParser

LogicManager -> GetTotalCommand: execute(model, activeAccount)
activate GetTotalCommand

alt is expense
GetTotalCommand -> Category: isExpense()
activate Category

Category --> GetTotalCommand
deactivate Category

GetTotalCommand -> ActiveAccount: getTotalExpenses()
activate ActiveAccount

ActiveAccount --> GetTotalCommand
deactivate ActiveAccount

else is revenue
GetTotalCommand -> Category: isRevenue()
activate Category

Category --> GetTotalCommand
deactivate Category

GetTotalCommand -> ActiveAccount: getTotalRevenue()
activate ActiveAccount

ActiveAccount --> GetTotalCommand
deactivate ActiveAccount

end

GetTotalCommand --> LogicManager
deactivate GetTotalCommand

deactivate LogicManager

@enduml
