@startuml
!include style.puml
skinparam arrowThickness 1.1

Class ExpenseBook MODEL_COLOR
Class UniqueExpenseList MODEL_COLOR
Class ObservableList MODEL_COLOR
Class Expense MODEL_COLOR
Class PieChartData MODEL_COLOR
Interface ChartDataCollector<<Interface>> MODEL_COLOR
Class GraphicalDisplayWindow UI_COLOR

ExpenseBook --> UniqueExpenseList
UniqueExpenseList *--> ObservableList
ObservableList --> Expense
ChartDataCollector <|.. PieChartData
PieChartData --> ExpenseBook
GraphicalDisplayWindow --> ChartDataCollector UI_COLOR

@enduml
