@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([not all ingredients have zero ingredient's levels])
    :Replace the ingredients that have
    non-zero ingredient's levels by new
    ingredient objects that have the
    same ingredient names and zero
    ingredient's levels;
    :Show a success message to the user;
else ([else])
    :Show an error message to the
    user stating that all ingredients
    already have zero ingredient's
    levels before the execution of the
    command;
endif
stop
@enduml
