@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class InventoryBook

Package Item {
Class Item
Class Supplier
Class MaxQuantity
Class Name
Class Metric
Class Quantity
Class UniqueItemList
Class UniqueTagList
Class Tag
}

InventoryBook *-right-> "1" UniqueTagList
InventoryBook *-right-> "1" UniqueItemList
UniqueTagList -[hidden]down- UniqueItemList
UniqueTagList -down-> "*" Tag

UniqueItemList o--> "*" Item
Item *--> Name
Item *--> Quantity
Item *--> Supplier
Item *--> MaxQuantity
Item *--> "*" Tag
Item *--> Metric

Name -[hidden]right-> Quantity
Quantity -[hidden]right-> Supplier
Supplier -[hidden]right-> MaxQuantity
MaxQuantity -[hidden]right-> Metric

@enduml
