@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ProductiveNusParser" as ProductiveNusParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant "l:ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "model:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("list 3")
activate LogicManager

LogicManager -> ProductiveNusParser : parseCommand("list 3")
activate ProductiveNusParser

create ListCommandParser
ProductiveNusParser -> ListCommandParser
activate ListCommandParser

ListCommandParser --> ProductiveNusParser
deactivate ListCommandParser

ProductiveNusParser -> ListCommandParser : parse("3")
activate ListCommandParser

create ListCommand
ListCommandParser -> ListCommand
activate ListCommand

ListCommand --> ListCommandParser : l
deactivate ListCommand

ListCommandParser --> ProductiveNusParser : l
deactivate ListCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
ListCommandParser -[hidden]-> ProductiveNusParser
destroy ListCommandParser

ProductiveNusParser --> LogicManager : l
deactivate ProductiveNusParser

LogicManager -> ListCommand : execute()
activate ListCommand

alt numberOfDays.getZeroBased() == 0

else else
ListCommand -> Model : updateFilteredAssignmentList(showLimitedAssignments())
activate Model
Model --> ListCommand
deactivate Model

end

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult -> Model : getFilteredAssignmentList()
activate Model
Model --> CommandResult : size of assignment list
deactivate Model
CommandResult --> ListCommand
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand

[<--LogicManager
deactivate LogicManager
@enduml
