@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant "command :ListCommand" as ListCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("userInput")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("userInput")
activate WishfulShrinkingParser

create ListCommand
WishfulShrinkingParser -> ListCommand
activate ListCommand

ListCommand --> WishfulShrinkingParser
deactivate ListCommand

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> ListCommand : execute()
activate ListCommand

ListCommand -> Model : getFilteredList()
activate Model

Model --> ListCommand : ObservableList<Type>
deactivate Model

create CommandResult
ListCommand -> CommandResult
activate CommandResult

CommandResult --> ListCommand
deactivate CommandResult

ListCommand --> LogicManager : result
deactivate ListCommand

[<--LogicManager
deactivate LogicManager
@enduml
