@startuml
start
:user inputs list command: recipes;
:Logic executes ListRecipeCommand;
if () then ([no extra arguments])
:recipe list is fetched;
else ([extra arguments present])
    :throw parse exception;
endif
stop

@enduml