@startuml
start
:user inputs list command: list;
:Logic executes list command;

if () then ([no extra arguments])
:execute ListCommand;

:all item in the list is fetched;

else ([extra argument is present])
    :throw parse exception;

endif
stop

@enduml