@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic {

package Parser {
Interface Parser <<Interface>>
Class ResiRegParser
Class XYZCommandParser
}

package Command {
Class XYZCommand
Class CommandResult
Class "{abstract}\nCommand" as Command
Class Help
Enum  CommandWordEnum <<enumeration>>
}

Interface Logic <<Interface>>
Class LogicManager
Class CommandHistory
}

package Model{
Class HiddenModel #FFFFFF
}

Class HiddenOutside #FFFFFF

HiddenOutside ..> Logic

/'
 ' Essentials
 '/
Logic ..> CommandResult

LogicManager .up.|> Logic
LogicManager --> Model
LogicManager ..> CommandResult
LogicManager ..> Command : executes >
LogicManager --> CommandHistory : adds to >
LogicManager ..> ResiRegParser : calls >
LogicManager ..> CommandWordEnum

CommandWordEnum ..> XYZCommand
CommandWordEnum --> Help
CommandWordEnum --> XYZCommandParser

Command ..> Model
Command ..> CommandResult

XYZCommand --|> Command
XYZCommand --> Help

XYZCommandParser ..|> Parser
XYZCommandParser ..> XYZCommand : creates >

ResiRegParser ..> Parser : calls >

@enduml
