@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StockBookParser" as StockBookParser LOGIC_COLOR
participant ":ListCommandParser" as ListCommandParser LOGIC_COLOR
participant ":ListAllCommand" as ListAllCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Commons LOGIC_COLOR_T1
participant ":SortUtil" as SortUtil << class >> LOGIC_COLOR
end box

[-> LogicManager : execute("list lt/all")
activate LogicManager

LogicManager -> StockBookParser : parseCommand("list lt/all")
activate StockBookParser

create ListCommandParser
StockBookParser -> ListCommandParser
activate ListCommandParser

ListCommandParser --> StockBookParser
deactivate ListCommandParser

StockBookParser -> ListCommandParser : parse("lt/all")
activate ListCommandParser

create ListAllCommand
ListCommandParser -> ListAllCommand
activate ListAllCommand

ListAllCommand --> ListCommandParser
deactivate ListAllCommand

ListCommandParser --> StockBookParser
deactivate ListCommandParser

StockBookParser --> LogicManager
deactivate StockBookParser

LogicManager -> ListAllCommand : execute()
activate ListAllCommand

ListAllCommand -> SortUtil : generateGeneralComparator()
activate SortUtil

SortUtil --> ListAllCommand
deactivate SortUtil

ListAllCommand -> Model : sortFilteredStockList()
activate Model

Model --> ListAllCommand
deactivate Model

ListAllCommand --> LogicManager
deactivate ListAllCommand

[<--LogicManager
deactivate LogicManager
@enduml
