@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class WishfulShrinking
Class ModelManager

Package Consumption {
Class ConsumptionList
Class Consumption

Package Recipe {
Class Recipe
Class Ingredient
Class Name
Class Calories
Class Instruction
Class RecipeImage
Class Tag
}

}


WishfulShrinking *--> "1" ConsumptionList
ConsumptionList--> "*" Consumption
Consumption--> "1" Recipe
Recipe *--> "1" Name
Recipe --> "1..*" Ingredient
Recipe *--> "1" Calories
Recipe *--> "1..*" Instruction
Recipe *--> "0..1" RecipeImage
Recipe *--> "*" Tag

Name -[hidden]right-> Ingredient
Ingredient -[hidden]right-> Calories
Calories -[hidden]right-> Instruction
Instruction -[hidden]right-> RecipeImage

ModelManager -->"1" Consumption: filtered consumption list
@enduml
