@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyModuleList <<Interface>>
Interface ReadOnlyContactList <<Interface>>
Interface ReadOnlyTodoList <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class ModuleList
Class ContactList
Class TodoList
Class ReadOnlyModuleList
Class ReadOnlyContactList
Class ReadOnlyTodoList
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModuleList .up.|> ReadOnlyModuleList
ContactList .up.|> ReadOnlyContactList
TodoList .up.|> ReadOnlyTodoList

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" ModuleList
ModelManager o--> "1" ContactList
ModelManager o--> "1" TodoList
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ModuleList *--> "1" UniqueModuleList
UniqueModuleList o--> "*" Module

ContactList *--> "1" UniqueContactList
UniqueContactList o--> "*" Contact

TodoList *--> "1" UniqueTodoList
UniqueTodoList o--> "*" Task

ModelManager -->"1" Module : filtered list
ModelManager -->"1" Contact : filtered list
ModelManager -->"1" Task : filtered list

@enduml
