@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class WishfulShrinking
Class ModelManager

Package Ingredient {
Class Ingredient
Class UniqueIngredientList
}


WishfulShrinking *-> "1" UniqueIngredientList
UniqueIngredientList o--> "*" Ingredient

ModelManager -->"1" Ingredient : filtered ingredient list
@enduml
