@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR


Class hidden #FFFF

Package Model <<Rectangle>>{
Interface ReadOnlyCommonCents <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class CommonCents
Class ReadOnlyCommonCents
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Account {
Class UniqueAccountList
Class Account
Class Name
Interface ActiveAccount
Class ActiveAccountManager



Package Entry {
Class ExpenseList
Class RevenueList
Abstract Class Entry
Class Expense
Class Revenue
Class Description
Class Amount
}
}

Package Tag {
Class Tag
}
}



hidden .down.|> Model

CommonCents .up.|> ReadOnlyCommonCents

ModelManager .up.|> Model
Model ..> ObservableList
ModelManager o--> "1" CommonCents
ModelManager o--> "1" UserPrefs
UserPrefs .down..|> ReadOnlyUserPrefs
ModelManager --> Account: filtered list

ActiveAccountManager "1" --> "0..1" ActiveAccountManager : previous state
ActiveAccountManager ..|> ActiveAccount
ActiveAccountManager o-left-> "1" Account

CommonCents *--> "1" UniqueAccountList
UniqueAccountList o--> "1..*" Account
Account *--> Name
Account *--> "1" ExpenseList
Account *--> "1" RevenueList

ExpenseList o--> "*" Expense
RevenueList o--> "*" Revenue
Expense .down.|> Entry
Revenue .down.|> Entry
Entry *--> Description
Entry *--> Amount
Entry *--> "*" Tag


@enduml
