@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyLogBook <<Interface>>
Interface Model <<Interface>>
Interface ObservableList <<Interface>>
Class LogBook
Class ReadOnlyLogBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Log {
Class Log
Class UniqueLogList
Class DateTime
Class Reps
Class Comment
}

Package Exercise {
Class Exercise
Class UniqueExerciseList
Class Name
Class Calories
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

LogBook .up.|> ReadOnlyLogBook

ModelManager .up.|> Model
Model .right.> ObservableList
ModelManager o--> "1" LogBook
ModelManager o-left-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

LogBook *--> "1" UniqueLogList
UniqueLogList o--> "*" Log
Log *-right-> Exercise
Log *--> DateTime
Log *--> Reps
Log *--> Comment

LogBook *--> "1" UniqueExerciseList
UniqueExerciseList o--> "*" Exercise
Exercise *--> Name
Exercise *--> Calories

ModelManager -->"1" Log : filtered list
ModelManager -->"1" Exercise : filtered list
@enduml
