@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

title Inside Recipe

Class WishfulShrinking
Class ModelManager

Package Recipe {
Class Recipe
Class Ingredient
Class Name
Class Calories
Class Instruction
Class Image
Class UniqueRecipeList
}

Package Tag {
Class Tag
}


WishfulShrinking *--> "1" UniqueRecipeList
UniqueRecipeList o--> "*" Recipe
Recipe *--> Name
Recipe *--> Ingredient
Recipe *--> Calories
Recipe *--> Instruction
Recipe *--> Image
Recipe --> "*" Tag

Name -[hidden]right-> Ingredient
Ingredient -[hidden]right-> Calories
Calories -[hidden]right-> Instruction
Instruction -[hidden]right-> Image

ModelManager -->"1" Recipe : filtered recipe list
@enduml
