@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Commands {
Class "{abstract}\nCommand" as Command
Class "{abstract}\nNegateCommand" as NegateCommand

Class UnremindCommand
Class UnprioritizeCommand
Class UndoneCommand
Class UndoCommand

NegateCommand -up-|> Command
UnremindCommand -up-|> NegateCommand
UnprioritizeCommand -up-|> NegateCommand
UndoneCommand -up-|> NegateCommand
UndoCommand -up-|> NegateCommand
}
@enduml
