@startuml
!include style.puml
scale 0.5

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
participant ":ReviewManager" as ReviewManager LOGIC_COLOR
end box

[-> MainWindow : executeCommand(commandText)
activate MainWindow

MainWindow -> LogicManager : execute(commandText)
activate LogicManager

LogicManager -> MainWindow : commandResult
deactivate LogicManager

MainWindow -> CommandResult : isReviewMode()
activate CommandResult
CommandResult -> MainWindow : true
deactivate CommandResult
CommandResult -[hidden]-> MainWindow
destroy CommandResult

MainWindow -> MainWindow : handleReview()
create ReviewManager
MainWindow -> ReviewManager
loop in review mode
    alt right arrow key
        MainWindow -> ReviewManager : hasNextFlashcard()
    else left arrow key
        MainWindow ->ReviewManager : hasPreviousFlashcard()
    end
end

@enduml
