@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class ModelManager
Class SalesBook
Interface ReadOnlySalesBook <<interface>>

Package SalesRecordEntry <<Rectangle>> {
Class UniqueSaleRecordList
Class SalesRecordEntry
Class Drink <<enumeration>>
Class Integer
}
}

Class HiddenOutside #FFFFFF
HiddenOutside .down.> SalesBook

ModelManager o-right-> "1" SalesBook
SalesBook .right.|> ReadOnlySalesBook

SalesBook *--> "1" UniqueSaleRecordList : record
UniqueSaleRecordList o--> "*" SalesRecordEntry
SalesRecordEntry *--> "1" Drink : drink
SalesRecordEntry *--> "1" Integer : numberSold

ModelManager -->"1" SalesRecordEntry : filteredSalesRecordList
@enduml
