@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":tCheckParser" as tCheckParser LOGIC_COLOR
participant ":SalesUpdateCommandParser" as SalesUpdateCommandParser LOGIC_COLOR
participant "s:SalesUpdateCommand" as SalesUpdateCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(salesUpdate)
activate LogicManager

LogicManager -> tCheckParser : parseCommand(salesUpdate)
activate tCheckParser

create SalesUpdateCommandParser
tCheckParser -> SalesUpdateCommandParser
activate SalesUpdateCommandParser

SalesUpdateCommandParser --> tCheckParser
deactivate SalesUpdateCommandParser

tCheckParser -> SalesUpdateCommandParser : parse(arguments)
activate SalesUpdateCommandParser

create SalesUpdateCommand
SalesUpdateCommandParser -> SalesUpdateCommand : SalesUpdateCommand(sales)
activate SalesUpdateCommand

SalesUpdateCommand --> SalesUpdateCommandParser
deactivate SalesUpdateCommand

SalesUpdateCommandParser --> tCheckParser : s
deactivate SalesUpdateCommandParser

SalesUpdateCommandParser -[hidden]-> LogicManager : result
destroy SalesUpdateCommandParser

tCheckParser --> LogicManager : s
deactivate tCheckParser

LogicManager -> SalesUpdateCommand : execute()
activate SalesUpdateCommand

SalesUpdateCommand -> Model : overwrite(sales)
activate Model

Model --> SalesUpdateCommand :
deactivate Model

create CommandResult
SalesUpdateCommand -> CommandResult : CommandResult(message)
activate CommandResult

CommandResult --> SalesUpdateCommand
deactivate CommandResult

SalesUpdateCommand --> LogicManager : result
deactivate SalesUpdateCommand

SalesUpdateCommand -[hidden]-> LogicManager : result
destroy SalesUpdateCommand

[<--LogicManager
deactivate LogicManager
@enduml
