@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([the command scope is valid])
    if () then ([the command is a coping command])
        :Update status;
        :Update project/task/etc. of focus;
    else ([else])
        :Execute the command on
         the objects of focus;
    endif
else ([else])
    :Throw an exception;
endif
stop
@enduml
