@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":SearchIngredientCommandParser" as SearchIngredientCommandParser LOGIC_COLOR
participant "command :SearchIngredientCommand" as SearchIngredientCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("searchF avocado")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("searchF avocado")
activate WishfulShrinkingParser

create SearchIngredientCommandParser
WishfulShrinkingParser -> SearchIngredientCommandParser
activate SearchIngredientCommandParser

SearchIngredientCommandParser --> WishfulShrinkingParser
deactivate SearchIngredientCommandParser

WishfulShrinkingParser -> SearchIngredientCommandParser : parse("avocado")
activate SearchIngredientCommandParser

create SearchIngredientCommand
SearchIngredientCommandParser -> SearchIngredientCommand
activate SearchIngredientCommand

SearchIngredientCommand --> SearchIngredientCommandParser
deactivate SearchIngredientCommand

SearchIngredientCommandParser --> WishfulShrinkingParser : command
deactivate SearchIngredientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SearchIngredientCommandParser -[hidden]-> WishfulShrinkingParser
destroy SearchIngredientCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> SearchIngredientCommand : execute()
activate SearchIngredientCommand

SearchIngredientCommand -> Model : updateFilteredIngredientList(predicate)
activate Model

Model --> SearchIngredientCommand : ObservableList<Ingredient>
deactivate Model

create CommandResult
SearchIngredientCommand -> CommandResult
activate CommandResult

CommandResult --> SearchIngredientCommand
deactivate CommandResult

SearchIngredientCommand --> LogicManager : result
deactivate SearchIngredientCommand

[<--LogicManager
deactivate LogicManager
@enduml
