@startuml
start
:user executes search command: search info;
:Logic executes search command;
:SearchCommandParser parses the command: search info;

    if () then ([fields to search for specified])
        if () then ([valid fields to search for specified])
        :execute SearchCommand;

            :items that fit the search are returned;

        else ([invalid fields to search for specified])
        :throw parse exception;
        endif

    else ([no fields to search for specified])
    :throw parse exception;
    endif

stop

@enduml
