@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant ":SelectRecipeCommandParser" as SelectRecipeCommandParser LOGIC_COLOR
participant "commsnd:SelectRecipeCommand" as SelectRecipeCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("selectR 1")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("delete 1")
activate WishfulShrinkingParser

create SelectRecipeCommandParser
WishfulShrinkingParser -> SelectRecipeCommandParser
activate SelectRecipeCommandParser

SelectRecipeCommandParser --> WishfulShrinkingParser
deactivate SelectRecipeCommandParser

WishfulShrinkingParser -> SelectRecipeCommandParser : parse("1")
activate SelectRecipeCommandParser

create SelectRecipeCommand
SelectRecipeCommandParser -> SelectRecipeCommand
activate SelectRecipeCommand

SelectRecipeCommand --> SelectRecipeCommandParser
deactivate SelectRecipeCommand

SelectRecipeCommandParser --> WishfulShrinkingParser : command
deactivate SelectRecipeCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
SelectRecipeCommandParser -[hidden]-> WishfulShrinkingParser
destroy SelectRecipeCommandParser

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> SelectRecipeCommand : execute()
activate SelectRecipeCommand

SelectRecipeCommand -> Model : getFilteredRecipeList()
activate Model

Model --> SelectRecipeCommand
deactivate Model

create CommandResult
SelectRecipeCommand -> CommandResult
activate CommandResult

CommandResult --> SelectRecipeCommand
deactivate CommandResult

SelectRecipeCommand --> LogicManager : result
deactivate SelectRecipeCommand

[<--LogicManager
deactivate LogicManager
@enduml
