@startuml
!include style.puml

Participant ":Taskmaster" as tm MODEL_COLOR
Participant ":Session" as s MODEL_COLOR
Participant ":StudentRecordListManager" as srlm MODEL_COLOR

[-> tm : markStudentAttendance(\n nusnetId, attendanceType)
activate tm
tm -> s ++: markStudentAttendance(\n nusnetId, attendanceType)

s -> srlm ++: markStudentAttendance(\n nusnetId, attendanceType)
srlm --> s --
s --> tm --
<-- tm --
@enduml
