@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR

Class Taskmaster

package Session {
    Class SessionList
    Class Session
    Interface StudentRecordList <<Interface>>
}

Taskmaster *--down-> "1" SessionList
SessionList *--right-> "*" Session
Taskmaster --down-> "1" Session
Session *--> "1" StudentRecordList

@enduml
