@startuml
!include ../style.puml

Participant ":Taskmaster" as tm MODEL_COLOR
Participant ":Session" as s MODEL_COLOR
Participant ":StudentRecordListManager" as srlm MODEL_COLOR
Participant "StudentRecord" as sr MODEL_COLOR

[-> tm : markStudentAttendance(\n nusnetId, attendanceType)
activate tm
tm -> s ++: markStudentAttendance(\n nusnetId, attendanceType)

s -> srlm ++: markStudentAttendance(\n nusnetId, attendanceType)
srlm -> sr ++: setAttendanceRecord(\n attendanceType)
sr --> srlm --
srlm --> s --
s --> tm --
tm --

@enduml