@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":tCheckParser" as tCheckParser LOGIC_COLOR
participant "s:SetCommand" as SetCommand LOGIC_COLOR

end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":IngredientBook" as IngredientBook MODEL_COLOR
participant ":UniqueIngredientList" as UniqueIngredientList MODEL_COLOR
end box

[-> LogicManager : execute(i-set i/Milk m/100)
activate LogicManager

LogicManager -> tCheckParser : parseCommand(i-set i/Milk m/100)
activate tCheckParser

create SetCommand
tCheckParser -> SetCommand
activate SetCommand

SetCommand --> tCheckParser
deactivate SetCommand

tCheckParser --> LogicManager : s
deactivate tCheckParser

LogicManager -> SetCommand : execute()
activate SetCommand

SetCommand -> Model : execute()

activate Model

Model -> IngredientBook : setIngredient(target, newAmount)
activate IngredientBook

IngredientBook -> UniqueIngredientList :setIngredient(target, newAmount)
activate UniqueIngredientList

UniqueIngredientList --> IngredientBook :
deactivate UniqueIngredientList

IngredientBook --> Model
deactivate IngredientBook

Model --> SetCommand
deactivate Model

SetCommand --> LogicManager : result
deactivate SetCommand
SetCommand -[hidden]-> LogicManager : result
destroy SetCommand

[<--LogicManager
deactivate LogicManager
@enduml
