@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title How Project and Person are associated

package  {
    class State1 as "__:Person__"
    class State2 as "__:Participation__"
    class State3 as "__:Project__"


State2 -left-> State1
State2 -right-> State3


@end
