@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
scale 0.5

title After command "sort leastReviewed"

package States {
    class ListState1 as "__ff1:ObservableList<Flashcard>__"
    class ListState2 as "__ff2:ObservableList<Flashcard>__"

    class Flashcard1State1 as "__fc1a:Flashcard__"
    class Flashcard2State1 as "__fc2a:Flashcard__"
    class Flashcard3State1 as "__fc3a:Flashcard__"

    class Flashcard1State2 as "__fc1b:Flashcard__"
    class Flashcard2State2 as "__fc2b:Flashcard__"
    class Flashcard3State2 as "__fc3b:Flashcard__"
}


ListState1 -[hidden]right-> ListState2
ListState2 -[hidden]right-> ListState3
hide ListState3


Flashcard1State1 --o ListState1
Flashcard2State1 --o ListState1
Flashcard3State1 --o ListState1

Flashcard1State2 --o ListState2
Flashcard2State2 --o ListState2
Flashcard3State2 --o ListState2

class Pointer as "Current State" #FFFFF
Pointer -up-> ListState2

@end
