@startuml
scale 0.5
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([sort by least to most reviewed])
    :Sorts sortedFlashcards
    by least to most reviewed;
else ([else])
    if () then ([sort by most to least reviewed])
        :Sorts sortedFlashcards
        by most to least reviewed;
    else ([else])
        if () then ([sort by lowest to highest success rate])
            :Sorts sortedFlashcards by
            lowest to highest success rate;
        else ([else])
            :Sorts sortedFlashcards by
            highest to lowest success rate;
         endif
    endif
endif
stop
@enduml
