@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package DataAnalysis {
    Class StatisticsData
    Class Statistics
}

package Model {
    Interface ObservableList <<Interface>>
    Class Task
    Class Lesson
    Class Tag
}

package UI {
    Class HiddenLogic #FFFFFF
}

StatisticsData ..> Task
StatisticsData ..> Lesson
StatisticsData ..> Tag
Statistics ..> StatisticsData
Statistics ..> ObservableList
UI -left-> StatisticsData
@enduml