@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STATE_COLOR
skinparam classBackgroundColor STATE_COLOR


Class StateManager
Class UIStateManager
Class Index


StateManager o--> "0..1" Index
StateManager .right.> UIStateManager
UIStateManager o--> "0..1" Index

@enduml
