@startuml
!include style.puml

box Ui UI_COLOR_T2
participant ":UiManager" as UiManager UI_COLOR_T3
participant ":MainWindow" as MainWindow UI_COLOR_T3
participant ":StatisticsWindow" as StatisticsWindow UI_COLOR_T3
participant ":CommandBox" as CommandBox UI_COLOR_T3
end box


[-> UiManager : start()
activate UiManager

UiManager -> MainWindow : fillInnerParts()
activate MainWindow

MainWindow -> MainWindow : executeCmd(cmdTxt)
activate MainWindow

MainWindow -> MainWindow : handleStats(data, details)
activate MainWindow

MainWindow -> StatisticsWindow : show(data, details);
activate StatisticsWindow

StatisticsWindow --> MainWindow
deactivate StatisticsWindow

MainWindow --> MainWindow
deactivate MainWindow

MainWindow --> MainWindow
deactivate MainWindow

create CommandBox
MainWindow -> CommandBox
activate CommandBox

CommandBox --> MainWindow
deactivate CommandBox

MainWindow --> UiManager
deactivate MainWindow

[<--UiManager
deactivate UiManager
@enduml
