@startuml
!include ./style.puml

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":Statistics" as stats LOGIC_COLOR
Participant ":StatisticsData" as std LOGIC_COLOR

activate logic
[-> logic: execute(model)
activate stats
logic -> stats: generateStatistics(countStartDate, now)
create std
stats -> std
stats -> stats: updateTimeTakenForTasks(...)
activate stats
stats -> std: addTag(currentTag)
activate std
std --> stats
deactivate std
stats -> std: addTaskTime(currentTag, timeTakenForTask)
activate std
std --> stats
deactivate std
return
stats -> stats: updateTimeTakenForLessons(...)

activate stats
stats -> std: addTag(currentTag)
activate std
std --> stats
deactivate std
stats -> std: addLessonTime(currentTag, timeTakenForLesson)
activate std
std --> stats
deactivate std
return
stats --> logic
deactivate stats
@enduml
