@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface PlanusStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonPlanusStorage

StorageManager .left.|> Storage
StorageManager o-right-> UserPrefsStorage
StorageManager o--> PlanusStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonPlanusStorage .left.|> PlanusStorage
JsonPlanusStorage .down.> JsonSerializablePlanus
JsonSerializablePlanus .right.> JsonSerializableEvent
JsonSerializablePlanus .down.> JsonSerializableDeadline
JsonSerializablePlanus .down.> JsonSerializableLesson
@enduml
