@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface InventoryBookStorage <<Interface>>
Interface DeliverBookStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonInventoryBookStorage
Class JsonDeliveryBookStorage

StorageManager .left.|> Storage
StorageManager o-right-> "1" UserPrefsStorage
StorageManager o--> "1" DeliverBookStorage
StorageManager o--> "1" InventoryBookStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonInventoryBookStorage .left.|> InventoryBookStorage
JsonInventoryBookStorage .down.> JsonSerializableInventoryBookStorage
JsonSerializableInventoryBookStorage .right.> JsonAdaptedItem
JsonAdaptedItem .right.> JsonAdaptedTag

JsonDeliveryBookStorage .up.|> DeliverBookStorage
JsonDeliveryBookStorage .down.> JsonSerializableDeliveryBookStorage
JsonSerializableDeliveryBookStorage .right.> JsonAdaptedDelivery
@enduml
