@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":StockBookParser" as StockBookParser LOGIC_COLOR
participant ":SuggestionCommandParser" as SuggestionCommandParser LOGIC_COLOR
participant ":SuggestionCommand" as SuggestionCommand LOGIC_COLOR
participant ":CommandException" as CommandException LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

box Commons MODEL_COLOR_T1
participant ":SuggestionUtil" as SuggestionUtil << class >> MODEL_COLOR
end box

[-> LogicManager : execute()
activate LogicManager

LogicManager -> StockBookParser : parseCommand(...)
activate StockBookParser

create SuggestionCommandParser
StockBookParser -> SuggestionCommandParser
activate SuggestionCommandParser

SuggestionCommandParser --> StockBookParser
deactivate SuggestionCommandParser

StockBookParser -> SuggestionCommandParser : parse(args)
activate SuggestionCommandParser

loop all command words
    SuggestionCommandParser -> SuggestionUtil : minimumEditDistance(...)
    activate SuggestionUtil

    SuggestionUtil --> SuggestionCommandParser
    deactivate SuggestionUtil
end

SuggestionCommandParser -> SuggestionCommandParser : generateUpdateSuggestion(...)
activate SuggestionCommandParser

SuggestionCommandParser --> SuggestionCommandParser
deactivate SuggestionCommandParser

create SuggestionCommand
SuggestionCommandParser -> SuggestionCommand
activate SuggestionCommand

SuggestionCommand --> SuggestionCommandParser
deactivate SuggestionCommand

SuggestionCommandParser --> StockBookParser
deactivate SuggestionCommandParser

StockBookParser --> LogicManager
deactivate StockBookParser

LogicManager -> SuggestionCommand : execute()
activate SuggestionCommand

SuggestionCommand -> Model : updateFilteredStockList(...)
activate Model

Model --> SuggestionCommand
deactivate Model

create CommandException
SuggestionCommand -> CommandException
activate CommandException

CommandException --> SuggestionCommand
deactivate CommandException

SuggestionCommand --> LogicManager
deactivate SuggestionCommand

[<--LogicManager
deactivate LogicManager
@enduml
