@startuml
!include style.puml

Participant ":TagCommand" as command LOGIC_COLOR
Participant "model:Model" as model MODEL_COLOR
Participant ":CommandResult" as result LOGIC_COLOR

[-> command: execute()

activate command

command -> model: hasTag()

activate model
model --> command: false
deactivate model

command -> command: filePresent()
activate command
command --> command: true
deactivate command

command -> model: addTag()
activate model
model --> command
deactivate model

command -> model: commitAddressBook()
activate model
model --> command
deactivate model

create result
command -> result:
activate result
result --> command
deactivate result

[<-- command: result
deactivate command
[-[hidden]-> command
destroy command

@enduml