@startuml
start
:StatisticsData tries to calculate time of a task;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([Event])
    :Calculate duration between
    start time and end time;
else ([Deadline])
    if () then ([Done])
        :Get its duration;
    else ([else])
        :Skip it;
    endif
endif
    :Add the time to total time;
stop
@enduml
