@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class IngredientListPanel
Class IngredientCard
Class SalesRecordListPanel
Class SalesRecordEntryCard
Class StatusBarFooter
Class CalendarView
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> PersonListPanel
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> IngredientListPanel
MainWindow *-down-> SalesRecordListPanel
MainWindow *-down-> CalendarView

PersonListPanel -down-> PersonCard
IngredientListPanel -down-> IngredientCard
SalesRecordListPanel -down-> SalesRecordEntryCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel --|> UiPart
IngredientListPanel --|> UiPart
SalesRecordListPanel --|> UiPart
CalendarView --|> UiPart
PersonCard --|> UiPart
SalesRecordEntryCard --|> UiPart
IngredientCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart

PersonCard ..> Model
IngredientCard ..> Model
SalesRecordEntryCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
