@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class RecipeListPanel
Class RecipeCard
Class IngredientListPanel
Class IngredientCard
Class ConsumptionListPanel
Class ConsumptionCard
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> RecipeListPanel
MainWindow *-down-> ConsumptionListPanel
MainWindow *-down-> IngredientListPanel
MainWindow *-down-> StatusBarFooter

RecipeListPanel -down-> RecipeCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
RecipeListPanel --|> UiPart
RecipeCard --|> UiPart
IngredientCard --|> UiPart
IngredientListPanel --|> UiPart
ConsumptionCard --|> UiPart
ConsumptionListPanel --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart

IngredientListPanel --> IngredientCard
ConsumptionListPanel --> ConsumptionCard

RecipeCard ..> Model
ConsumptionCard ..> Model
IngredientCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

RecipeListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
