@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package Model <<Rectangle>> {
}

Model <.down. UpcomingAssignmentCard
Model <.right. AssignmentCard
Model <.up. ReminderCard
Model <.left. UpcomingLessonCard

@enduml
