@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class StaffListPanel
Class StaffCard
Class ApplicantListPanel
Class ApplicantCard
Class StatusBarFooter
Class CommandBox
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> StaffListPanel
MainWindow *-down-> ApplicantListPanel
MainWindow *-down-> StatusBarFooter

StaffListPanel -down-> StaffCard
ApplicantListPanel -down-> ApplicantCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
StaffListPanel --|> UiPart
StaffCard --|> UiPart
ApplicantListPanel --|> UiPart
ApplicantCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart

StaffCard ..> Model
ApplicantCard ..> Model

UiManager -right-> Logic
MainWindow -left-> Logic

StaffListPanel -[hidden]left- HelpWindow
ApplicantListPanel -[hidden]left- StaffListPanel
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
