@startuml
!include style.puml

box StateManager STATE_COLOR_T1
participant "StateManager" as StateManager STATE_COLOR
participant "UiStateManager" as UiStateManager STATE_COLOR
end box

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR_T1
end box

[-> StateManager : setState(Index)
activate StateManager

StateManager -> UiStateManager : setCasePanelState(Index)
activate UiStateManager

UiStateManager -> MainWindow : notifyObservers()
activate MainWindow

MainWindow -> MainWindow : updateCaseInformationPanel(Index)

MainWindow --> UiStateManager
deactivate MainWindow

UiStateManager --> StateManager
deactivate UiStateManager

[<-- StateManager
deactivate StateManager
@enduml
