@startuml
start
:User executes unassign command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if() then ([no modules specified])
    :Unassign specified contact from all modules it is assigned to;
else([else])
    if () then ([all modules exist])
        if () then ([contact is assigned to
   all modules specified])
            :Unassign specified contact from specified modules;
            :Update GUI to show changes;

        else([else])
            : Show error message;
        endif


    else ([else])
        : Show error message;
    endif
endif
stop
@enduml
