@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title When Common Cents is initialized.

package States <<rectangle>> {
    class State1 as "__aa1:ActiveAccountManager__"
    class State2 as "__aa1:ActiveAccountManager__"
}

State1 -[hidden]right-> State2

hide State2

class Pointer as "Current State" #FFFFF

Pointer -up-> State1
@end
