@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":EvaParser" as EvaParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedEvaStorage" as VersionedEvaStorage MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> EvaParser : parseCommand(undo)
activate EvaParser

create UndoCommand
EvaParser -> UndoCommand
activate UndoCommand

UndoCommand --> EvaParser
deactivate UndoCommand

EvaParser --> LogicManager : u
deactivate EvaParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoAddressBook()
activate Model

Model -> VersionedEvaStorage : undo()
activate VersionedEvaStorage

VersionedEvaStorage -> VersionedEvaStorage :resetData(ReadOnlyEvaDatabase)
VersionedEvaStorage --> Model :
deactivate VersionedEvaStorage

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
