@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "list-i"

package States <<rectangle>>{
    class InventoryState1 as "__ib0:InventoryBook__"
    class DeliveryState1 as "__db0:DeliveryBook__"
    class InventoryState2 as "__ib1:InventoryBook__"
    class DeliveryState2 as "__db1:DeliveryBook__"
    class InventoryState3 as "__ib2:InventoryBook__"
    class DeliveryState3 as "__db2:DeliveryBook__"
    class Pointer as "Current State" #FFFFF
}
InventoryState1 -[hidden]right-> InventoryState2
InventoryState2 -[hidden]right-> InventoryState3

DeliveryState1 -[hidden]right-> DeliveryState2
DeliveryState2 -[hidden]right-> DeliveryState3

Pointer -up-> InventoryState2
Pointer -down-> DeliveryState2
@end
