@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":InventoryinatorParser" as InventoryinatorParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedInventoryinator" as VersionedInventoryinator MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> InventoryinatorParser : parseCommand(undo)
activate InventoryinatorParser

create UndoCommand
InventoryinatorParser -> UndoCommand
activate UndoCommand

UndoCommand --> InventoryinatorParser
deactivate UndoCommand

InventoryinatorParser --> LogicManager : u
deactivate InventoryinatorParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoInventoryinator()
activate Model

Model -> VersionedInventoryinator : undo()
activate VersionedInventoryinator

VersionedInventoryinator -> VersionedInventoryinator :resetData(ReadOnlyInventoryinator)
VersionedInventoryinator --> Model :
deactivate VersionedInventoryinator

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
