@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "list"

package States {
    class State1 as "__currState:ResiReg__"
    package undoStatesStack {
        class State2 as "__stateBeforeClear:ResiReg__"
        class State4 as "__stateBeforeDelete:ResiReg__"
    }
    package redoStatesStack { }
}

State1-[hidden]right-> undoStatesStack
State1-[hidden]right-> redoStatesStack
undoStatesStack-[hidden]right-> redoStatesStack

class Pointer1 as "Top Element" #FFFFF

Pointer1 -up-> State2
note top of redoStatesStack
stack is cleared
end note
@enduml
