@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package States {
    class State1 as "__currState:ResiReg__"
    package redoStatesStack { }
    package undoStatesStack { }
}
State1-[hidden]right->undoStatesStack
State1-[hidden]right->redoStatesStack
@end
