@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "addmodule n/CS2103T​"

package States <<rectangle>> {
    class State1 as "__ml0:ModuleList__"
    class State2 as "__ml1:ModuleList__"
    class State3 as "__ml2:ModuleList__"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFF

Pointer -up-> State3
@end
