@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "undo"

package States {
    class State1 as "__currState:ResiReg__"
    package redoStatesStack {
        class State2 as "__stateAfterAdd:ResiReg__"
    }
    package undoStatesStack {
        class State3 as "__stateBeforeDelete:ResiReg__"
    }
}

State1-[hidden]right-> undoStatesStack
State1-[hidden]right-> redoStatesStack
redoStatesStack-[hidden]right-> undoStatesStack

class Pointer1 as "Top Element" #FFFFF
class Pointer2 as "Top Element" #FFFFF

Pointer1 -up-> State2
Pointer2 -up-> State3
@end
