@startuml
!include style.puml
skinparam ParticipantFontSize 30
skinparam ArrowFontSize 28
skinparam defaultFontSize 28

box LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ProductiveNusParser" as ProductiveNusParser LOGIC_COLOR
participant ":UndoCommand" as UndoCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("undo")
activate LogicManager

LogicManager -> ProductiveNusParser : parseCommand("undo")
activate ProductiveNusParser

create UndoCommand
ProductiveNusParser -> UndoCommand : UndoCommand("")
activate UndoCommand

UndoCommand -> ProductiveNusParser
deactivate UndoCommand

ProductiveNusParser --> LogicManager
deactivate ProductiveNusParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : getPreviousModel
activate Model
Model --> UndoCommand : previousModel
deactivate Model

UndoCommand -> Model : goToPreviousModel
activate Model
Model --> UndoCommand
deactivate Model

create CommandResult
UndoCommand -> CommandResult : CommandResult()
activate CommandResult

CommandResult --> UndoCommand
deactivate CommandResult

UndoCommand --> LogicManager : result
deactivate UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
