@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Command "delete 5", before deleting

package Stack {
    class State1 as "__copy0:ReadOnlyMcGymmy__"
    class State2 as "__copy1:ReadOnlyMcGymmy__"
    class State3 as "__copy2:AddressBook__"
}


State1 -[hidden]up-> State2
State2 -[hidden]up-> State3

hide State2
hide State3

class McGymmy as "Current McGymmy" #FFFFF
McGymmy -left-> State1: make copy
@end
