@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Command "add -n Rice ...", after adding

package Stack {
    class State1 as "__copy0:Pair<ReadOnlyMcGymmy, Predicate<Food>>__"
    class State2 as "__copy1:Pair<ReadOnlyMcGymmy, Predicate<Food>>__"
    class State3 as "__copy2:Pair<ReadOnlyMcGymmy, Predicate<Food>>__"
}


State1 -[hidden]up-> State2
State2 -[hidden]up-> State3

hide State3

class ModelManager as "Updated ModelManager" #FFFFF
ModelManager -[hidden]left-> State3
@end
