@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":FlashcardDeckParser" as FlashcardDeckParser LOGIC_COLOR
participant ":UnfavCommandParser" as UnfavCommandParser LOGIC_COLOR
participant "u:UnfavCommand" as UnfavCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Flashcard MODEL_COLOR_T2
participant "flashcardToUnfavourite:Flashcard" as Flashcard MODEL_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("unfav 1")
activate LogicManager

LogicManager -> FlashcardDeckParser : parseCommand("unfav 1")
activate FlashcardDeckParser

create UnfavCommandParser
FlashcardDeckParser -> UnfavCommandParser
activate UnfavCommandParser

UnfavCommandParser --> FlashcardDeckParser
deactivate UnfavCommandParser

FlashcardDeckParser -> UnfavCommandParser : parse("1")
activate UnfavCommandParser

create UnfavCommand
UnfavCommandParser -> UnfavCommand
activate UnfavCommand

UnfavCommand --> UnfavCommandParser : u
deactivate UnfavCommand

UnfavCommandParser --> FlashcardDeckParser : u
deactivate UnfavCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
UnfavCommandParser -[hidden]-> FlashcardDeckParser
destroy UnfavCommandParser

FlashcardDeckParser --> LogicManager : u
deactivate FlashcardDeckParser

LogicManager -> UnfavCommand : execute()
activate UnfavCommand

UnfavCommand -> Flashcard : isFavourite()
activate Flashcard

Flashcard -> UnfavCommand : isFavourite
deactivate Flashcard

opt flashcard is favourited

    UnfavCommand -> UnfavCommand : createUnfavouriteFlashcard(flashcardToUnfavourite)
    activate UnfavCommand

    UnfavCommand -> UnfavCommand : unfavouritedFlashcard
    deactivate UnfavCommand

    UnfavCommand -> Model : setFlashcard(flashcardToUnfavourite, unfavouritedFlashcard)
    activate Model

    Model --> UnfavCommand
    deactivate Model

    UnfavCommand -> Model : updateFilteredFlashcardList(PREDICATE_SHOW_ALL_FLASHCARDS);
    activate Model

    Model --> UnfavCommand
    deactivate Model

    end

create CommandResult
UnfavCommand -> CommandResult
activate CommandResult

CommandResult --> UnfavCommand
deactivate CommandResult

UnfavCommand --> LogicManager : result
deactivate UnfavCommand

[<--LogicManager
deactivate LogicManager
@enduml
