@startuml
start
:User executes update command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

:Obtain existing Exercise;

:Create a new, updated Exercise;

:Replace original Exercise with \nupdated Exercise in UniqueExerciseList;

stop
@enduml
