@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial state

package commandHistory {
    class command as "__delete 5:String__"
    class initState as "__empty:String__"
}

initState -[hidden]right-> command

hide command

class Pointer as "Current State" #FFFFF
Pointer -up-> initState
@end
