@startuml
!include ../style.puml

Participant ":LogicManager" as logic LOGIC_COLOR
Participant ":OneShelfBookParser" as osbp LOGIC_COLOR
Participant ":ItemEditCommandParser" as ecp LOGIC_COLOR
Participant "command:EditCommand" as ec LOGIC_COLOR

[-> logic : execute
activate logic
logic -> osbp ++: parseCommand(commandText)
create ecp
osbp -> ecp
osbp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editItemDescriptor
ec --> ecp --
ecp --> osbp --: command
osbp --> logic --: command

@enduml
