@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WishfulShrinkingParser" as WishfulShrinkingParser LOGIC_COLOR
participant "l:ListRecipesCommand" as ListRecipesCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":WishfulShrinking" as WishfulShrinking MODEL_COLOR
participant ":UniqueRecipeList" as UniqueRecipeList MODEL_COLOR
end box

[-> LogicManager : execute("recipes")
activate LogicManager

LogicManager -> WishfulShrinkingParser : parseCommand("recipes")
activate WishfulShrinkingParser

create ListRecipesCommand
WishfulShrinkingParser -> ListRecipesCommand
activate ListRecipesCommand

ListRecipesCommand --> WishfulShrinkingParser
deactivate ListRecipesCommand

WishfulShrinkingParser --> LogicManager : command
deactivate WishfulShrinkingParser

LogicManager -> ListRecipesCommand : execute()
activate ListRecipesCommand

ListRecipesCommand -> Model : updateFilteredRecipeList()
activate Model

Model -> WishfulShrinking : getRecipeList()
activate WishfulShrinking

WishfulShrinking -> UniqueRecipeList : asUnmodifiableObservableList()
activate UniqueRecipeList

UniqueRecipeList -> WishfulShrinking
deactivate UniqueRecipeList

WishfulShrinking -> Model
deactivate WishfulShrinking

Model -> ListRecipesCommand
deactivate Model

Model --> ListRecipesCommand
deactivate Model

create CommandResult
ListRecipesCommand -> CommandResult
activate CommandResult

CommandResult --> ListRecipesCommand
deactivate CommandResult

ListRecipesCommand --> LogicManager : result
deactivate ListRecipesCommand

[<--LogicManager
deactivate LogicManager
@enduml
