title: "Modduke"
plugins:
  - jemoji
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: solarized

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "ay2021s1-cs2103-f10-2/tp"
github_icon: "images/github-icon.png"


