title: "DSAce"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "https://github.com/AY2021S1-CS2103-T14-2/tp.git"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
