title: "ResiReg"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-T16-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
