title: "Fine$$e"
theme: minima

header_pages:
  - GanttChart.md
  - Minutes.md
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

kramdown:
  parse_block_html: true

repository: "AY2021S1-CS2103T-W16-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  # Disabled since we are building the files manually.
  # - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-spaceship
