title: "CliniCal"
theme: jekyll-theme-cayman

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-W11-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji

kramdown:
  toc_levels: 1..4
