title: "ATAS"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

kramdown:
  parse_block_html: true

repository: "AY2021S1-CS2103T-W16-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
