title: "IntelliBrary App"
remote_theme: jekyll-theme-yat

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103-F10-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
