title: "GradPad"
theme: jekyll-theme-hacker

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-T09-1/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
