@startuml
start
:Agent executes delete command
according to appropriate index;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([else])
    :Error message sent to
    agent indicating wrong index
    is given in the command;

else ([bidder index exists])
    :Bidder corresponding to the
    index parsed will be deleted;
    :Save updated BidderAddressBook
    to addressBookStateList;
endif
stop

@enduml
