@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteBidderCommandParser" as DeleteBidderCommandParser LOGIC_COLOR
participant "d:DeleteBidderCommand" as DeleteBidderCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete-b 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("delete 1")
activate AddressBookParser

create DeleteBidderCommandParser
AddressBookParser -> DeleteBidderCommandParser
activate DeleteBidderCommandParser

DeleteBidderCommandParser --> AddressBookParser
deactivate DeleteBidderCommandParser

AddressBookParser -> DeleteBidderCommandParser : parse("1")
activate DeleteBidderCommandParser

create DeleteBidderCommand
DeleteBidderCommandParser -> DeleteBidderCommand
activate DeleteBidderCommand

DeleteBidderCommand --> DeleteBidderCommandParser : d
deactivate DeleteBidderCommand

DeleteBidderCommandParser --> AddressBookParser : d
deactivate DeleteBidderCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteBidderCommandParser -[hidden]-> AddressBookParser
destroy DeleteBidderCommandParser

AddressBookParser --> LogicManager : d
deactivate AddressBookParser

LogicManager -> DeleteBidderCommand : execute()
activate DeleteBidderCommand

DeleteBidderCommand -> Model : deleteBidder(1)
activate Model

Model --> DeleteBidderCommand
deactivate Model

create CommandResult
DeleteBidderCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteBidderCommand
deactivate CommandResult

DeleteBidderCommand --> LogicManager : result
deactivate DeleteBidderCommand

[<--LogicManager
deactivate LogicManager
@enduml
