name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          # Ubuntu Linux (trusty) / Oracle JDK 8 / Headed (AWT Robot)
          - os: linux
            dist: trusty
            jdk: oraclejdk8
            env:
              - _JAVA_OPTIONS="-Dtestfx.robot=awt"
          # Ubuntu Linux (trusty) / Oracle JDK 8 / Headed (Glass Robot) / HiDPI
          - os: linux
            dist: trusty
            jdk: oraclejdk8
            env:
              - _JAVA_OPTIONS="-Dtestfx.robot=glass -Dglass.gtk.uiScale=2.0"
          # Ubuntu Linux (trusty) / Oracle JDK 8 / Headless
          - os: linux
            dist: trusty
            jdk: oraclejdk8
            env:
              - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw"
          # macOS / Oracle JDK 8 / Headless
          - os: osx
            osx_image: xcode9.4
            jdk: oraclejdk8
            env:
              - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.verbose=true"
          # Headed macOS is not currently possible on Travis.
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@master

      - name: Set up repository
        uses: actions/checkout@master
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Run repository-wide tests
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/.github
        run: ./run-checks.sh

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk+fx

      - name: Build and check with Gradle
        run: ./gradlew check coverage

      - uses: codecov/codecov-action@v1
        if: runner.os == 'Linux'
        with:
          file: ${{ github.workspace }}/build/reports/jacoco/coverage/coverage.xml
          fail_ci_if_error: true
